# Generated by Django 6.0.5 on 2026-05-16 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'Ativo'), (0, 'Inativo')], default=1)),
            ],
            options={
                'db_table': 'especialidade',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'Ativo'), (0, 'Inativo')], default=1)),
            ],
            options={
                'db_table': 'servico',
            },
        ),
        migrations.CreateModel(
            name='UsuarioSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'Ativo'), (0, 'Inativo')], default=1)),
            ],
            options={
                'db_table': 'usuario_sistema',
            },
        ),
        migrations.CreateModel(
            name='Dentista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=11, unique=True)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'Ativo'), (0, 'Inativo')], default=1)),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appcore.especialidade')),
            ],
            options={
                'db_table': 'dentista',
            },
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_paciente', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('endereco', models.TextField()),
                ('data_consulta', models.DateField()),
                ('hora_consulta', models.TimeField()),
                ('status_consulta', models.CharField(choices=[('AGENDADO', 'Agendado'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='AGENDADO', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'Ativo'), (0, 'Inativo')], default=1)),
                ('dentista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appcore.dentista')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appcore.servico')),
            ],
            options={
                'db_table': 'agendamento',
            },
        ),
    ]
