# Generated by Django 6.0.5 on 2026-05-14 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dentista',
            fields=[
                ('cod_dentista', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('cro', models.CharField(max_length=30, unique=True)),
                ('telefone', models.CharField(db_comment='Telefone celular sem formatacao, 11 digitos: DDD + numero', max_length=15, unique=True)),
                ('especialidade', models.CharField(max_length=100)),
                ('data_cadastro', models.DateField()),
                ('status', models.IntegerField(blank=True, db_comment='Ativo (1) ou Inativo (0)', null=True)),
            ],
            options={
                'db_table': 'dentista',
                'db_table_comment': 'Registra os dados profissionais e de contato dos dentistas.',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('cod_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(db_comment='CPF sem pontos ou tracos, exatamente 11 digitos numericos', max_length=14, unique=True)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(db_comment='Telefone celular sem formatacao, 11 digitos: DDD + n·mero', max_length=15, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('data_cadastro', models.DateField()),
                ('status', models.IntegerField(blank=True, db_comment='Ativo (1) ou Inativo (0)', null=True)),
            ],
            options={
                'db_table': 'paciente',
                'db_table_comment': 'Registra as informacoes pessoais e de contato dos pacientes.',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('cod_procedimento', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('data_cadastro', models.DateField()),
                ('status', models.IntegerField(blank=True, db_comment='Ativo (1) ou Inativo (0)', null=True)),
            ],
            options={
                'db_table': 'procedimento',
                'db_table_comment': 'Catalogo de procedimentos odontologicos realizados na clinica.',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsuarioSistema',
            fields=[
                ('cod_usuario_sistema', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('tipo_usuario', models.CharField(db_comment='(1) Administrador | (2) Recepcionista', max_length=1)),
                ('data_cadastro', models.DateField()),
                ('status', models.IntegerField(blank=True, db_comment='Ativo (1) ou Inativo (0)', null=True)),
            ],
            options={
                'db_table': 'usuario_sistema',
                'db_table_comment': 'Armazena os dados de acesso e perfis dos usuarios do sistema.',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('cod_endereco', models.AutoField(primary_key=True, serialize=False)),
                ('cep', models.CharField(db_comment='Sem tracos ou pontos, exatamente 8 digitos numericos', max_length=15)),
                ('rua', models.CharField(max_length=150)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=150)),
                ('estado', models.CharField(max_length=50)),
                ('data_cadastro', models.DateField()),
                ('status', models.IntegerField(blank=True, db_comment='Ativo (1) ou Inativo (0)', null=True)),
                ('cod_paciente', models.OneToOneField(db_column='cod_paciente', on_delete=django.db.models.deletion.DO_NOTHING, to='appcore.paciente')),
            ],
            options={
                'db_table': 'endereco',
                'db_table_comment': 'Armazena os endereþos residenciais vinculados a cada paciente.',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('cod_consulta', models.AutoField(primary_key=True, serialize=False)),
                ('data_consulta', models.DateField()),
                ('hora_consulta', models.TimeField()),
                ('status_consulta', models.CharField(blank=True, max_length=20, null=True)),
                ('motivo_cancelamento', models.CharField(blank=True, db_comment='Preenchido apenas se a consulta for CANCELADO', max_length=80, null=True)),
                ('data_cadastro', models.DateField()),
                ('status', models.IntegerField(blank=True, db_comment='Ativo (1) ou Inativo (0)', null=True)),
                ('cod_dentista', models.ForeignKey(db_column='cod_dentista', on_delete=django.db.models.deletion.DO_NOTHING, to='appcore.dentista')),
                ('cod_paciente', models.ForeignKey(db_column='cod_paciente', on_delete=django.db.models.deletion.DO_NOTHING, to='appcore.paciente')),
                ('cod_procedimento', models.ForeignKey(db_column='cod_procedimento', on_delete=django.db.models.deletion.DO_NOTHING, to='appcore.procedimento')),
            ],
            options={
                'db_table': 'consulta',
                'db_table_comment': 'Gerencia o agendamento e o historico de consultas clÝnicas do paciente.',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='paciente',
            name='cod_usuario_sistema',
            field=models.ForeignKey(db_column='cod_usuario_sistema', on_delete=django.db.models.deletion.DO_NOTHING, to='appcore.usuariosistema'),
        ),
        migrations.CreateModel(
            name='Disponibilidade',
            fields=[
                ('cod_disponibilidade', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(max_length=50)),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('data_cadastro', models.DateField()),
                ('status', models.IntegerField(blank=True, db_comment='Ativo (1) ou Inativo (0)', null=True)),
                ('cod_dentista', models.ForeignKey(db_column='cod_dentista', on_delete=django.db.models.deletion.DO_NOTHING, to='appcore.dentista')),
            ],
            options={
                'db_table': 'disponibilidade',
                'db_table_comment': 'Armazena os horßrios de atendimento semanais de cada dentista.',
                'managed': True,
                'unique_together': {('dia_semana', 'horario_inicio', 'horario_fim', 'cod_dentista')},
            },
        ),
    ]
