# Generated by Django 6.0.5 on 2026-05-18 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('cod_especialidade', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'Ativo'), (0, 'Inativo')], default=1)),
            ],
            options={
                'db_table': 'especialidade',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('cod_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('endereco', models.CharField(max_length=255)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'Ativo'), (0, 'Inativo')], default=1)),
            ],
            options={
                'db_table': 'paciente',
            },
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('cod_procedimento', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'Ativo'), (0, 'Inativo')], default=1)),
            ],
            options={
                'db_table': 'procedimento',
            },
        ),
        migrations.CreateModel(
            name='UsuarioSistema',
            fields=[
                ('cod_usuario_sistema', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'Ativo'), (0, 'Inativo')], default=1)),
            ],
            options={
                'db_table': 'usuario_sistema',
            },
        ),
        migrations.CreateModel(
            name='Dentista',
            fields=[
                ('cod_dentista', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=15, unique=True)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'Ativo'), (0, 'Inativo')], default=1)),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appcore.especialidade')),
            ],
            options={
                'db_table': 'dentista',
            },
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('cod_agendamento', models.AutoField(primary_key=True, serialize=False)),
                ('data_consulta', models.DateField()),
                ('hora_consulta', models.TimeField()),
                ('status_agendamento', models.IntegerField(choices=[(1, 'AGENDADO'), (2, 'CONCLUIDO'), (3, 'CANCELADO')], default=1)),
                ('motivo_cancelamento', models.TextField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('dentista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appcore.dentista')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appcore.paciente')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appcore.procedimento')),
            ],
            options={
                'db_table': 'agendamento',
            },
        ),
    ]
