# Generated by Django 6.0.5 on 2026-05-16 03:32

from django.db import migrations

def carregar_dados_iniciais(apps, schema_editor):
    # Recupera os modelos usando o histórico do Django
    Servico = apps.get_model('appcore', 'Servico')
    Especialidade = apps.get_model('appcore', 'Especialidade')
    
    # 1. Lista de Serviços
    lista_servicos = [
        'LIMPEZA', 'CLAREAMENTO', 'APARELHOS ORTODÔNTICOS', 
        'TRATAMENTO DE GENGIVAS', 'FACETAS', 'MANUTENÇÃO', 
        'FRENECTOMIA', 'REMOÇÃO DE LESÃO PATOLÓGICA', 
        'CIRURGIA DE REGULARIZAÇÃO DE REBORDO ALVEOLAR', 
        'PRÓTESE ADESIVA', 'AUMENTO DE COROA CLÍNICA', 
        'GENGIVOPLASTIA', 'PROVISÓRIO', 'PLACA PARA BRUXISMO', 'CONTENÇÃO'
    ]
    
    for nome_servico in lista_servicos:
        Servico.objects.get_or_create(nome=nome_servico)
        
    # 2. Lista de Especialidades
    lista_especialidades = [
        'CLÍNICA GERAL',
        'ORTODONTIA',
        'ENDODONTIA',
        'PERIODONTIA',
        'IMPLANTODONTIA',
        'ODONTOPEDIATRIA',
        'PRÓTESE DENTÁRIA',
        'CIRURGIA E TRAUMATOLOGIA BUCO-MAXILO-FACIAL'
    ]
    
    for nome_especialidade in lista_especialidades:
        Especialidade.objects.get_or_create(nome=nome_especialidade)


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0001_initial'), # Garante que as novas tabelas já existem no banco
    ]

    operations = [
        migrations.RunPython(carregar_dados_iniciais), # Executa a carga de dados acima
    ]