# Generated by Django 6.0.5 on 2026-05-17 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0002_auto_20260516_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_paciente', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('endereco', models.TextField()),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'Ativo'), (0, 'Inativo')], default=1)),
            ],
            options={
                'db_table': 'paciente',
            },
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='email',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='nome_paciente',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='telefone',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='appcore.paciente'),
            preserve_default=False,
        ),
    ]
